projects:
  adv:
    schemaPath: src/graphql/schema.json
    includes:
      - src/graphql/queries/**/*.js
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: src/graphql/queries
        maxDepth: 2
extensions:
  amplify:
    version: 3
